"""
Django settings for BulletinBoard project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-85a-5djgq%(7n3a(7&o-^9^fua@^6raflfodvym4mv_#+1a-vr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Setting for allauth
    'board',
    'rest_framework',
    'accounts',
    'allauth',  # Setting for allauth
    'allauth.account',  # Setting for allauth
    'allauth.socialaccount',  # Setting for allauth
    'ckeditor',
    'ckeditor_uploader', 
]

SITE_ID = 1 # Setting for allauth
CKEDITOR_PLUGIN_PATH = os.path.join(BASE_DIR, 'static', 'ckeditor', 'plugins')
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 300,
        'width': 'auto',
        'extraPlugins': ','.join([
            'uploadimage',  # Плагин для загрузки изображений
            'uploadfile',   # Плагин для загрузки файлов
            'embed',         # Плагин для вставки медиа-контента
            'embedbase',
            'autolink',
            'font',          # Плагин для управления шрифтами
            'colorbutton',   # Плагин для изменения цвета текста и фона
            'youtube',       # Плагин для вставки YouTube видео
            'html5video',    # Плагин для вставки HTML5 видео
        ]),
        'filebrowserUploadUrl': '/ckeditor/upload/',  # URL для загрузки файлов
        'filebrowserBrowseUrl': '/ckeditor/browse/',  # URL для выбора файлов
        'toolbar_Full': [
            ['Bold', 'Italic', 'Underline', 'Strike'],  # Основные стили текста
            ['Font', 'FontSize'],                      # Шрифт и размер шрифта
            ['TextColor', 'BGColor'],                  # Цвет текста и фона
            ['Image', 'Table', 'Link', 'Unlink', 'Anchor'],
            ['Embed'],                                # Вставка эмбед-кода
            ['MediaEmbed'],                           # Вставка медиа контента
            ['YouTube'],                              # Вставка YouTube видео
            ['Html5Video'],                           # Вставка HTML5 видео
            ['UploadFile'],                           # Загрузка файлов
            ['Source'],                               # Просмотр исходного кода
        ],
        'font_names': 'Arial; Comic Sans MS; Courier New; Georgia; Tahoma; Times New Roman; Verdana',  # Список доступных шрифтов
        'fontSize_sizes': '12/12px;14/14px;16/16px;18/18px;24/24px;36/36px;48/48px;',  # Доступные размеры
    },
}

CKEDITOR_UPLOAD_PATH = "uploads/"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Settings for allauth
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'BulletinBoard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'accounts', 'templates', 'allauth')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Setting for allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Setting for allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'


WSGI_APPLICATION = 'BulletinBoard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'
LANGUAGES = [('ru', 'Русский'), ('en-us', 'English')]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_FORMS = {"signup": "accounts.forms.CustomSignupForm"}
# email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = "anim.news@yandex.ru"
EMAIL_HOST_PASSWORD = "jzfjrtppxabamvrk"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = "anim.news@yandex.ru"
SERVER_EMAIL = "anim.news@yandex.ru"
MANAGERS = (('AnimeNews', 'anim.news.@yandex.ru'),
            ('example', 'example@yandex.ru'))
ADMINS = [('AnimeNews', 'anim.news.@yandex.ru')]