# Generated by Django 5.1.3 on 2024-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseboard',
            name='is_accept',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, default='boards/images/default_image.jpg', null=True, upload_to='boards/images/'),
        ),
    ]
